### PR TITLE
Fix broken function renames

### LINKED ISSUE #47: Postgres 12->13 upgrade fail due to function not present in binary
Bumped into three issues during upgrade. Might be my dev builds, might be more serious leftovers of functions that are pointing to nowhere in binaries.

```
pg_restore: from TOC entry 2374; 1255 18901 FUNCTION h3_get_h3_unidirectional_edge_boundary("public"."h3index") gis
pg_restore: error: could not execute query: ERROR:  could not find function "h3_get_unidirectional_edge_boundary" in file "/usr/lib/postgresql/13/lib/h3.so"
Command was: CREATE FUNCTION "public"."h3_get_h3_unidirectional_edge_boundary"("edge" "public"."h3index") RETURNS "polygon"
    LANGUAGE "c" IMMUTABLE STRICT PARALLEL SAFE
    AS 'h3', 'h3_get_unidirectional_edge_boundary';

...


pg_restore: from TOC entry 2023; 1255 18919 FUNCTION h3_set_to_multi_polygon("public"."h3index"[]) gis
pg_restore: error: could not execute query: ERROR:  could not find function "h3_set_to_linked_geo" in file "/usr/lib/postgresql/13/lib/h3.so"
Command was: CREATE FUNCTION "public"."h3_set_to_multi_polygon"("public"."h3index"[], OUT "exterior" "polygon", OUT "holes" "polygon"[]) RETURNS SETOF "record"
    LANGUAGE "c" IMMUTABLE STRICT PARALLEL SAFE
    AS 'h3', 'h3_set_to_linked_geo';

....

pg_restore: creating INDEX "public.covid19_population_h3_r6_h3_idx"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 6963; 1259 3204505732 INDEX covid19_population_h3_r6_h3_idx gis
pg_restore: error: could not execute query: ERROR:  type "geometry" does not exist
LINE 1:  SELECT ST_SetSRID(h3_to_geo($1)::geometry, 4326) 
                                          ^
QUERY:   SELECT ST_SetSRID(h3_to_geo($1)::geometry, 4326) 
CONTEXT:  SQL function "h3_to_geometry" during inlining
Command was: 
-- For binary upgrade, must preserve pg_class oids
SELECT pg_catalog.binary_upgrade_set_next_index_pg_class_oid('3204505732'::pg_catalog.oid);

CREATE INDEX "covid19_population_h3_r6_h3_idx" ON "public"."covid19_population_h3_r6" USING "gist" ((("h3")::"public"."geometry"));


```

### LINKED ISSUE #86: Updating from v3.7.2 to v4.0.0 breaks some functions
Functions that are renamed and not re-created in `h3--3.7.2--4.0.0.sql` are left linked to old C function names, that are no longer available.

To reproduce:
* install v3.7.2;
* create extension;
* install v4.0.0;
* update extension;
* execute query: `select h3_polygon_to_cells(st_setsrid(st_geomfromtext('POLYGON ((30 60,  31 60, 31 61, 30 61, 30 60))'),4326)::polygon, array[]::polygon[], 8)`:
  `[42883] ERROR: could not find function "h3_polyfill" in file "/usr/local/pgsql/lib/h3.so"`

### PR DESCRIPTION
**Pull request by zachasme**
Thanks to @Komzpa and @mngr777 I finally know how to properly handle C-level function renames.

Previously we went back and altered the upgrade-scripts (so the rest of the tests could pass), but in hindsight that was a bad idea.

This PR tries to restore the upgrade-scripts, and adds stub C functions (inspired by postgis) instead.

At this point, user installations could be in pretty different states, which should be taken into account.

I've started out with a simple commit with a failing test, exposing the issue. I'll need to create the proper upgrade script as well.

Closes #86.
Closes #47.

### CODE REVIEW

**Comment by zachasme** [comment]
@Komzpa + @mngr777: I went with a combination of your suggestions, which will be to stub out old C-functions and do an `alter function <...> rename to <...>; create or replace function <...>`.

In order to align user-installations as much as possible I've copied almost the entire installation script into the next upgrade (except types/casts/operators/operator classes). This makes also the new test pass.

How do you feel about this approach?

File: h3/src/deprecated.c [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+#define H3_DEPRECATE(version, funcname) \
+	PG_FUNCTION_INFO_V1(funcname); \
+	Datum funcname(PG_FUNCTION_ARGS) \
+	{ \
+		ereport(ERROR, (\
+			errcode(ERRCODE_FEATURE_NOT_SUPPORTED), \
+			errmsg("A stored procedure tried to use deprecated C function '%s'", \
+			       __func__), \
+			errdetail("Library function '%s' was deprecated in PostGIS %s", \
```
Comment (Komzpa) [inline h3/src/deprecated.c:31]:
```suggestion
			errdetail("Library function '%s' was deprecated in h3 %s", \
```

**Comment by Komzpa** [comment]
Upgrade scripts running in ALTER EXTENSION contexts glue and unglue the functions to extensions automatically, you are not supposed to run the extensions upgrade scripts manually - in this case indeed you need to attach/detach functions manually.

If you moved some functions between extensions, I don't know how to do that starting PG15 anymore - previously you could unpackage the functions and then CREATE EXTENSION FROM unpackaged; now it is forbidden for security reasons. So drop & create new.

Probably some drops are just lost in the upgrade script?

PostGIS has weird upgrade scripts that need to account for many kinds of broken installs fixed by drunk monkeys, so upgrading from the state where someone removed a function that was supposed to be there should be supported, that's why the weird construct.

**Comment by mngr777** [comment]
I just had some update files left in Postgres extension directory.
Everything seems to work after I removed them.
Sorry about that.

**Comment by zachasme** [comment]
Thanks for the input, I've released a new version that should fix the broken functions.
